### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by dora-babu** [mmin18/Dex65536#1]
Hi,

  I have downloaded the project and followed all the steps you have mentioned.  i have ant installed on my system.The project was building successfully if i used just "ant" command on the root directory of the project but i get the following error if i use "ant debug" command.

BUILD FAILED
C:\Users\3124\Downloads\Reference_Materials\Dex65536-master\Dex65536\custom_rule
s.xml:26: null returned: 1.

I dont have a clue as to what is going wrong. so can someone explain what had i done wrong.

**Comment by marvinlix** [comment]
just mkdir the assets dir.

**Comment by mmin18** [comment]
@marvinlix is correct. and i just commit some code to fix that.
now you can also "ant debug install run"
