### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by veerendrapolepalli** [mmin18/Dex65536#2]
H:\software\dex>ant debug install run
Buildfile: H:\software\dex\build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 22.6.0
 [checkenv] Installed at D:\adt-bundle-windows-x86\sdk

-setup:
     [echo] Project Name: MainActivity
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 19.0.3
     [echo] Resolving Build Target for MainActivity...
[gettarget] Project Target:   Android 4.3
[gettarget] API level:        18
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: H:\software\dex\bin
    [mkdir] Created dir: H:\software\dex\bin\res
    [mkdir] Created dir: H:\software\dex\bin\rsObj
    [mkdir] Created dir: H:\software\dex\bin\rsLibs
    [mkdir] Created dir: H:\software\dex\gen
    [mkdir] Created dir: H:\software\dex\bin\classes
    [mkdir] Created dir: H:\software\dex\bin\dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for MainActivity...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency]
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...
   [subant] No sub-builds to iterate on

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 10 source files to H:\software\dex\bin\classes

-post-compile:
 [pathtool] include H:\software\dex\libs\10k-methods.jar
 [pathtool] include H:\software\dex\libs\android-support-v4.jar
    [mkdir] Created dir: H:\software\dex\bin\libs.apk
      [dex] Converting compiled files and external libraries into H:\software\dex\bin\libs.apk\classes.
       [dx] no input files specified
       [dx] usage:
       [dx]   dx --dex [--debug] [--verbose] [--positions=<style>] [--no-locals]
       [dx]   [--no-optimize] [--statistics] [--[no-]optimize-list=<file>] [--no-strict]
       [dx]   [--keep-classes] [--output=<file>] [--dump-to=<file>] [--dump-width=<n>]
       [dx]   [--dump-method=<name>[*]] [--verbose-dump] [--no-files] [--core-library]
       [dx]   [--num-threads=<n>] [--incremental] [--force-jumbo]
       [dx]   [--multi-dex [--main-dex-list=<file> [--minimal-main-dex]]
       [dx]   [<file>.class | <file>.{zip,jar,apk} | <directory>] ...
       [dx]     Convert a set of classfiles into a dex file, optionally embedded in a
       [dx]     jar/zip. Output name must end with one of: .dex .jar .zip .apk or be a directory.
       [dx]     Positions options: none, important, lines.
       [dx]     --multi-dex: allows to generate several dex files if needed. This option is
       [dx]     exclusive with --incremental, causes --num-threads to be ignored and only
       [dx]     supports folder or archive output.
       [dx]     --main-dex-list=<file>: <file> is a list of class file names, classes defined by
       [dx]     those class files are put in classes.dex.
       [dx]     --minimal-main-dex: only classes selected by --main-dex-list are to be put in
       [dx]     the main dex.
       [dx]   dx --annotool --annotation=<class> [--element=<element types>]
       [dx]   [--print=<print types>]
       [dx]   dx --dump [--debug] [--strict] [--bytes] [--optimize]
       [dx]   [--basic-blocks | --rop-blocks | --ssa-blocks | --dot] [--ssa-step=<step>]
       [dx]   [--width=<n>] [<file>.class | <file>.txt] ...
       [dx]     Dump classfiles, or transformations thereof, in a human-oriented format.
       [dx]   dx --find-usages <file.dex> <declaring type> <member>
       [dx]     Find references and declarations to a field or method.
       [dx]     declaring type: a class name in internal form, like Ljava/lang/Object;
       [dx]     member: a field or method name, like hashCode
       [dx]   dx -J<option> ... <arguments, in one of the above forms>
       [dx]     Pass VM-specific options to the virtual machine that runs dx.
       [dx]   dx --version
       [dx]     Print the version of this tool (1.8).
       [dx]   dx --help
       [dx]     Print this message.

BUILD FAILED
H:\software\dex\custom_rules.xml:26: null returned: 1

i took the updated clone still i am getting the same build failed error , can u please suggest me with this .....

**Comment by kebbbnnn** [comment]
Hi, I'm also facing the same issue. null returned in custom_rules.xml:26
hope there's someone could explain this..tnx

**Comment by leotu** [comment]
+1

**Comment by mmin18** [comment]
updated the pathtool.jar, should be working in windows now.

**Comment by HungryT** [comment]
+1
